"""PCO Resources models.

Generated by pypco_generator tool. Manual changes not recommended.
"""

#pylint: disable=C0321,R0903,C0111

from .base_model import BaseModel

# The base Resources model
class ResourcesModel(BaseModel): pass

# Resources Models
class Attachment(ResourcesModel): 
    """    An uploaded file.
"""
    ENDPOINT_NAME='attachments'

class Conflict(ResourcesModel): 
    """A Conflict between two events caused by overlapping event resource
requests.
"""
    ENDPOINT_NAME='conflicts'

class Event(ResourcesModel): 
    """An event.
"""
    ENDPOINT_NAME='events'

class EventInstance(ResourcesModel): 
    """A specific occurence of an event.
"""
    ENDPOINT_NAME='event_instances'

class EventResourceRequest(ResourcesModel): 
    """A request of a resource for a specific event.
"""
    ENDPOINT_NAME='event_resource_requests'

class EventTime(ResourcesModel): 
    """Start and end times used for calendar and kiosk visibility for each
Event Instance.
"""
    ENDPOINT_NAME='event_instances'

class Person(ResourcesModel): 
    """The people in your organization.
"""
    ENDPOINT_NAME='people'

class Resource(ResourcesModel): 
    """A room or resource (equipment) that can be requested for use as part of
an event.
"""
    ENDPOINT_NAME='resources'

class ResourceApprovalGroup(ResourcesModel): 
    """    A group of people that can be attached to resources in order to require
    their approval.
"""
    ENDPOINT_NAME='resource_approval_groups'

class ResourceBooking(ResourcesModel): 
    """A specific booking of a resource for an event instance.
"""
    ENDPOINT_NAME='resource_bookings'

class ResourceFolder(ResourcesModel): 
    """An organizational folder containing rooms or resources.
"""
    ENDPOINT_NAME='resource_folders'

class ResourceQuestion(ResourcesModel): 
    """A question to answer when requesting to book a resource.
"""
    ENDPOINT_NAME='resource_questions'

class ResourceSuggestion(ResourcesModel): 
    """A resource and quantity suggested by a room setup.
"""
    ENDPOINT_NAME='room_setups'

class RoomSetup(ResourcesModel): 
    """A diagram and list of suggested resources useful for predefined room setups.
"""
    ENDPOINT_NAME='room_setups'
