"""PCO Giving endpoints.

Generated by pypco_generator tool. Manual changes not recommended.
"""

#pylint: disable=C0304,R0903,C0111,C0321

from .base_endpoint import BaseEndpoint

# The base Giving endpoint
class GivingEndpoint(BaseEndpoint): pass

# All Giving endpoints
class BatchGroups(GivingEndpoint):
    """None"""
    pass

class Batches(GivingEndpoint):
    """None"""
    pass

class Donations(GivingEndpoint):
    """None"""
    pass

class Funds(GivingEndpoint):
    """None"""
    pass

class Labels(GivingEndpoint):
    """None"""
    pass

class PaymentSources(GivingEndpoint):
    """None"""
    pass

class People(GivingEndpoint):
    """None"""
    pass

class RecurringDonations(GivingEndpoint):
    """None"""
    pass
