"""PCO People endpoints.

Generated by pypco_generator tool. Manual changes not recommended.
"""

#pylint: disable=C0304,R0903,C0111,C0321

from .base_endpoint import BaseEndpoint

# The base People endpoint
class PeopleEndpoint(BaseEndpoint): pass

# All People endpoints
class Addresses(PeopleEndpoint):
    """An address represents a physical and/or mailing address for a person."""
    pass

class Apps(PeopleEndpoint):
    """An app is one of the handful of apps that PCO offers that organizations can subscribe to, e.g. Services, Registrations, etc."""
    pass

class Campuses(PeopleEndpoint):
    """A Campus is a location belonging to an Organization"""
    pass

class Carriers(PeopleEndpoint):
    """None"""
    pass

class Emails(PeopleEndpoint):
    """An email represents an email address and location."""
    pass

class FieldData(PeopleEndpoint):
    """A field datum is an individual piece of data for a custom field."""
    pass

class FieldDefinitions(PeopleEndpoint):
    """A field definition represents a custom field -- its name, data type, etc."""
    pass

class Forms(PeopleEndpoint):
    """A custom form for people to fill out."""
    pass

class Households(PeopleEndpoint):
    """A household links people together and can have a primary contact. To add a person to an existing household, use the HouseholdMemberships endpoint."""
    pass

class InactiveReasons(PeopleEndpoint):
    """An inactive reason is a small bit of text indicating why a member is no longer active."""
    pass

class ListCategories(PeopleEndpoint):
    """A List Category"""
    pass

class Lists(PeopleEndpoint):
    """A list is a powerful tool for finding and grouping people together using any criteria imaginable."""
    pass

class MaritalStatuses(PeopleEndpoint):
    """A martial status represents a member's current status, e.g. married, single, etc."""
    pass

class MessageGroups(PeopleEndpoint):
    """A message group represents one or more emails or text messages sent from one of the Planning Center apps. The message group indicates the from person, app, etc."""
    pass

class Messages(PeopleEndpoint):
    """A message is an individual email or sms text sent to a member. Every message has a parent message group."""
    pass

class NamePrefixes(PeopleEndpoint):
    """A name prefix is one of Mr., Mrs., etc."""
    pass

class NameSuffixes(PeopleEndpoint):
    """A name suffix is one of Sr., Jr., etc."""
    pass

class NoteCategories(PeopleEndpoint):
    """A Note Category"""
    pass

class NoteCategorySubscriptions(PeopleEndpoint):
    """A subscription for note categories"""
    pass

class Notes(PeopleEndpoint):
    """A note is text with a category connected to a person’s profile."""
    pass

class People(PeopleEndpoint):
    """A person record represents a single member/user of the application. Each person has different permissions that determine how the user can use this app (if at all)."""
    pass

class PeopleImports(PeopleEndpoint):
    """A PeopleImport is a record of an ongoing or previous import from a CSV file."""
    pass

class PersonMergers(PeopleEndpoint):
    """A Person Merger is the history of profiles that were merged into other profiles."""
    pass

class Reports(PeopleEndpoint):
    """A report is editable liquid syntax that provides  a powerful tool for presenting your Lists however you want."""
    pass

class SchoolOptions(PeopleEndpoint):
    """A school option represents a school name, school type, grades, etc. and can be selected for a person."""
    pass

class SocialProfiles(PeopleEndpoint):
    """A social profile represents a members's Twitter, Facebook, or other social media account."""
    pass

class Stats(PeopleEndpoint):
    """Returns statistics for the organization."""
    pass

class Tabs(PeopleEndpoint):
    """A tab is a custom tab and groups like field definitions."""
    pass

class Workflows(PeopleEndpoint):
    """A Workflow"""
    pass
