"""PCO Resources endpoints.

Generated by pypco_generator tool. Manual changes not recommended.
"""

#pylint: disable=C0304,R0903,C0111,C0321

from .base_endpoint import BaseEndpoint

# The base Resources endpoint
class ResourcesEndpoint(BaseEndpoint): pass

# All Resources endpoints
class Attachments(ResourcesEndpoint):
    """    An uploaded file.
"""
    pass

class Conflicts(ResourcesEndpoint):
    """A Conflict between two events caused by overlapping event resource
requests.
"""
    pass

class EventInstances(ResourcesEndpoint):
    """A specific occurence of an event.
"""
    pass

class EventResourceRequests(ResourcesEndpoint):
    """A request of a resource for a specific event.
"""
    pass

class Events(ResourcesEndpoint):
    """An event.
"""
    pass

class People(ResourcesEndpoint):
    """The people in your organization.
"""
    pass

class ResourceApprovalGroups(ResourcesEndpoint):
    """    A group of people that can be attached to resources in order to require
    their approval.
"""
    pass

class ResourceBookings(ResourcesEndpoint):
    """A specific booking of a resource for an event instance.
"""
    pass

class ResourceFolders(ResourcesEndpoint):
    """An organizational folder containing rooms or resources.
"""
    pass

class ResourceQuestions(ResourcesEndpoint):
    """A question to answer when requesting to book a resource.
"""
    pass

class Resources(ResourcesEndpoint):
    """A room or resource (equipment) that can be requested for use as part of
an event.
"""
    pass

class RoomSetups(ResourcesEndpoint):
    """A diagram and list of suggested resources useful for predefined room setups.
"""
    pass
