"""PCO Services endpoints.

Generated by pypco_generator tool. Manual changes not recommended.
"""

#pylint: disable=C0304,R0903,C0111,C0321

from .base_endpoint import BaseEndpoint

# The base Services endpoint
class ServicesEndpoint(BaseEndpoint): pass

# All Services endpoints
class AttachmentTypes(ServicesEndpoint):
    """Create an Attachment Type for each type of file you might want only specific people to see. When you attach a file, you can specify an attachment type to then be able to link the file to a position."""
    pass

class EmailTemplates(ServicesEndpoint):
    """A EmailTemplate Resource"""
    pass

class Folders(ServicesEndpoint):
    """A folder is a container used to organize multiple Service Types or other Folders."""
    pass

class Media(ServicesEndpoint):
    """A piece of media"""
    pass

class People(ServicesEndpoint):
    """A person added to PCO Services."""
    pass

class Series(ServicesEndpoint):
    """A Series can be specified for each plan to tie plans with similar messages together, even across Service Types.

*Note*: A series is not created until artwork is added from the plan.  You can use `series_title` included in `Plan` attributes to get titles for series without artwork.
"""
    pass

class ServiceTypes(ServicesEndpoint):
    """A Service Type is a container for plans."""
    pass

class Songs(ServicesEndpoint):
    """A song"""
    pass

class TagGroups(ServicesEndpoint):
    """A tag group contains tags"""
    pass

class Teams(ServicesEndpoint):
    """A Team within a Service Type."""
    pass
