"""PCO Webhooks endpoints.

Generated by pypco_generator tool. Manual changes not recommended.
"""

#pylint: disable=C0304,R0903,C0111,C0321

from .base_endpoint import BaseEndpoint

# The base Webhooks endpoint
class WebhooksEndpoint(BaseEndpoint): pass

# All Webhooks endpoints
class AvailableEvents(WebhooksEndpoint):
    """An event supported by webhooks"""
    pass

class Subscriptions(WebhooksEndpoint):
    """None"""
    pass
